apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: status-web
  namespace: monitoring-manual
  labels:
    app.kubernetes.io/name: status-web
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: status-web
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
