apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring-manual
type: Opaque
stringData:
  thanos.yaml: |
    type: S3
    config:
      bucket: thanos
      endpoint: minio.monitoring-manual.svc:9000
      access_key: minio
      secret_key: minio123
      insecure: true
